In [3]:
import numpy as np
import pandas as pd

# Câu 1
arr1 = np.random.randint(0, 21, size=(3, 3))
print(np.all(arr1 != 0))

# Câu 2
arr2 = np.random.randint(0, 21, size=(3, 3))
print(np.any(arr2 != 0))

# Câu 3
a, b = np.array([1, 5]), np.array([2, 5])
print(np.greater(a, b), np.greater_equal(a, b), np.less(a, b), np.less_equal(a, b))

# Câu 4
arr4 = np.concatenate([np.ones(10), np.zeros(10), np.full(10, 5)])

# Câu 5
arr5 = np.arange(30, 71, 2)

# Câu 6
arr6 = np.identity(3)

# Câu 7
arr7 = np.linspace(15, 55, 10)
print(arr7[1:-1])

# Câu 8
arr8 = np.arange(21)
arr8[(arr8 >= 9) & (arr8 <= 15)] *= -1

# Câu 9
arr9 = np.random.randint(10, 22, size=(3, 4))

# Câu 10
arr10 = np.ones((10, 10))
arr10[1:-1, 1:-1] = 0

# Câu 11
arr11 = np.diag([1, 2, 3, 4, 5])

# Câu 12
arr12 = np.random.randint(1, 10, size=(3, 3, 3))
print(np.sum(arr12, axis=1), np.sum(arr12, axis=2))

# Câu 13
v1, v2 = np.random.rand(10), np.random.rand(10)
print(np.dot(v1, v2))

# Câu 14
A = np.random.randint(1, 10, size=(4, 3))
y = np.array([10, 20, 30])
print(A + y)

# Câu 15 (Vectorize hàm maxx)
def maxx(x, y): return x if x >= y else y
pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max([1, 5, 7], [2, 4, 8]))

# Câu 16 (Hoán đổi cột 1 và 2)
arr16 = np.arange(9).reshape(3,3)
print(arr16[:, [1, 0, 2]])

# Câu 17 (Hoán đổi dòng 1 và 2)
print(arr16[[1, 0, 2], :])

# Câu 18 (Đảo ngược các dòng)
print(arr16[::-1])

# Câu 19 (Đảo ngược các cột)
print(arr16[:, ::-1])

# Câu 20
arr20 = np.random.rand(20)

# Câu 21
x_ser = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y_ser = pd.Series(['p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'])
print(pd.concat([x_ser, y_ser], axis=0))
print(pd.concat([x_ser, y_ser], axis=1))

# Câu 22
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
df = pd.DataFrame(exam_data)

# Câu 23
print(df.head(3))

# Câu 24
print(df[['name', 'score']])

# Câu 25
print(df[df['attempts'] > 2])

# Câu 26
print(df.shape)

# Câu 27
print(df[df['score'].isnull()])

# Câu 28
print(df[df['score'].between(15, 20)])

# Câu 29
df.at[0, 'score'] = 11.5

# Câu 30
print(df['attempts'].sum())

True
True
[False False] [False  True] [ True False] [ True  True]
[19.44444444 23.88888889 28.33333333 32.77777778 37.22222222 41.66666667
 46.11111111 50.55555556]
[[17 15 12]
 [ 9 15 26]
 [13 15 22]] [[11 20 13]
 [21 14 15]
 [11 16 23]]
1.724196013889591
[[12 26 33]
 [14 25 32]
 [11 26 31]
 [19 21 38]]
[2. 5. 8.]
[[1 0 2]
 [4 3 5]
 [7 6 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object
   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y
        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
        name  score
0  Anastasia   12.5
1       Dima    9.0
2  Katherine   16.5
3      James    NaN
4      Emily    9.0
5    Michael   20.0
6    Matthew   14.5
7      Laura    N

# Mục mới