In [14]:
import tensorflow as tf
from tensorflow.keras import layers, models
# --- CÂU 1 ---
t1 = tf.zeros([2, 3])
print(f"Câu 1:\n{t1.numpy()}\n")

# --- CÂU 2 ---
X = [[1, 2, 3], [4, 5, 6]]
t2 = tf.zeros_like(X)
print(f"Câu 2:\n{t2.numpy()}\n")

# --- CÂU 3 ---
t3 = tf.fill([3, 2], 5)
print(f"Câu 3:\n{t3.numpy()}\n")

# --- CÂU 4 ---
t4 = tf.linspace(6.0, 10.0, 50) # 50 phần tử trong đoạn chứa các số chẵn
print(f"Câu 4 (5 phần tử đầu):\n{t4[:5].numpy()}\n")

# --- CÂU 5 ---
t5 = tf.range(10, 101, delta=2)
print(f"Câu 5:\n{t5.numpy()}\n")

# --- CÂU 6 ---
t6 = tf.random.normal([3, 2], mean=0, stddev=2)
print(f"Câu 6:\n{t6.numpy()}\n")

# --- CÂU 7 ---
t7 = tf.random.uniform([3, 2], minval=0, maxval=2)
print(f"Câu 7:\n{t7.numpy()}\n")

# --- CÂU 8 ---
X8 = tf.constant([[1, 2], [3, 4], [5, 6]])
t8 = tf.random.shuffle(X8)
print(f"Câu 8 (Sau shuffle):\n{t8.numpy()}\n")

# --- CÂU 9 ---
t9_orig = tf.random.uniform([10, 10, 3])
t9_crop = tf.image.random_crop(t9_orig, size=[5, 5, 3])
print(f"Câu 9 (Shape sau crop): {t9_crop.shape}\n")

# --- CÂU 10 ---
x10 = tf.constant([1.0, 5.0, 3.0])
y10 = tf.constant([2.0, 4.0, 6.0])
t10 = tf.where(x10 < y10, x10 + y10, x10 - y10)
print(f"Câu 10: {t10.numpy()}\n")

# --- CÂU 11 ---
x11 = tf.random.uniform([3, 2], 5, 10)
y11 = tf.random.uniform([2, 3], 15, 20)
res11 = tf.matmul(x11, y11)
print(f"Câu 11 (Matmul):\n{res11.numpy()}\n")

# --- CÂU 12 ---
@tf.function
def compute_ops(x, y):
    return x + y, x - y, x * y, x / y
c12 = compute_ops(tf.constant(10.0), tf.constant(2.0))
print(f"Câu 12 (Cộng, Trừ, Nhân, Chia): {[v.numpy() for v in c12]}\n")

# --- CÂU 13 ---
class SumModel(tf.Module):
    @tf.function
    def __call__(self, x, y):
      return tf.add(x, y)
print(f"Câu 13 (Tổng 5+7): {SumModel()(5, 7).numpy()}\n")

# --- CÂU 14 ---
class MathModel(tf.Module):
    @tf.function
    def __call__(self, x, y): return x - y, x * y
print(f"Câu 14 (Hiệu, Tích 10 & 3): {[v.numpy() for v in MathModel()(10.0, 3.0)]}\n")

# --- CÂU 15 ---
class PerimeterModel(tf.keras.Model):
    def __init__(self):
        super(PerimeterModel, self).__init__()

    @tf.function
    def call(self, inputs):
        a, b = inputs
        return tf.multiply(tf.add(a, b), 2.0)

model_p = PerimeterModel()
# Ví dụ: a=5, b=3 -> P=16
print("Câu 15: \n")
print(model_p((tf.constant(5.0), tf.constant(3.0))))
# --- CÂU 16 ---
class TotalAreaModel(tf.keras.Model):
    def __init__(self):
        super(TotalAreaModel, self).__init__()

    @tf.function
    def call(self, inputs):
        # inputs gồm (chiều dài a, chiều rộng b, chiều cao c)
        a, b, c = inputs

        # S_xung_quanh = (a + b) * c * 2
        s_xq = tf.multiply(tf.multiply(tf.add(a, b), c), 2.0)

        # S_day = a * b * 2
        s_day = tf.multiply(tf.multiply(a, b), 2.0)

        # S_toan_phan = S_day + S_xung_quanh
        s_tp = tf.add(s_day, s_xq)

        return s_tp

model_area = TotalAreaModel()
# Ví dụ: a=2, b=3, c=4
# S_xq = (2+3)*4*2 = 40; S_day = 2*3*2 = 12 -> S_tp = 52
print("Câu 16: \n")
print(model_area((tf.constant(2.0), tf.constant(3.0), tf.constant(4.0))))
# --- CÂU 17 ---
def build_model():
    model = models.Sequential([
        # Input layer: nhận 8 tọa độ hoặc 4 độ dài cạnh
        layers.Input(shape=(8,)),

        # Hidden layers để học các mối quan hệ phi tuyến (như tính độ dài cạnh từ tọa độ)
        layers.Dense(16, activation='relu'),
        layers.Dense(8, activation='relu'),

        # Output layer: dùng Sigmoid cho bài toán phân loại nhị phân
        layers.Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    return model
print("Câu 17: \n")
model = build_model()
model.summary()



Câu 1:
[[0. 0. 0.]
 [0. 0. 0.]]

Câu 2:
[[0 0 0]
 [0 0 0]]

Câu 3:
[[5 5]
 [5 5]
 [5 5]]

Câu 4 (5 phần tử đầu):
[6.        6.0816326 6.163265  6.244898  6.3265305]

Câu 5:
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]

Câu 6:
[[ 0.3936921 -1.2863984]
 [ 1.2180014 -1.5467577]
 [ 1.345322   3.0907407]]

Câu 7:
[[1.8151035  1.5995362 ]
 [1.752795   1.43805   ]
 [1.0812964  0.88935614]]

Câu 8 (Sau shuffle):
[[5 6]
 [3 4]
 [1 2]]

Câu 9 (Shape sau crop): (5, 5, 3)

Câu 10: [3. 1. 9.]

Câu 11 (Matmul):
[[248.96774 253.56354 293.70447]
 [231.39612 237.4147  270.50497]
 [247.30074 252.13249 291.36078]]

Câu 12 (Cộng, Trừ, Nhân, Chia): [np.float32(12.0), np.float32(8.0), np.float32(20.0), np.float32(5.0)]

Câu 13 (Tổng 5+7): 12

Câu 14 (Hiệu, Tích 10 & 3): [np.float32(7.0), np.float32(30.0)]

Câu 15: 

tf.Tensor(16.0, shape=(), dtype=float32)
Câu 16: 



Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_30 (Dense)                │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_31 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 289 (1.13 KB)

 Trainable params: 289 (1.13 KB)

 Non-trainable params: 0 (0.00 B)